// WebAssembly wrapper for the C Snake game
// This file will be generated by Emscripten, but this shows how to integrate it

let gameModule = null;
let wasmReady = false;

// Initialize WebAssembly module
async function initWasmGame() {
    try {
        // Load the WebAssembly module
        gameModule = await createGameModule();
        wasmReady = true;
        
        // Initialize the game
        gameModule._init_game();
        
        console.log('WebAssembly game loaded successfully!');
        return true;
    } catch (error) {
        console.error('Failed to load WebAssembly game:', error);
        return false;
    }
}

// Wrapper class for WebAssembly game
class WasmSnakeGame {
    constructor(canvasId) {
        this.canvas = document.getElementById(canvasId);
        this.ctx = this.canvas.getContext('2d');
        this.gridSize = 20;
        this.tileCount = this.canvas.width / this.gridSize;
        this.gameRunning = false;
        this.gameLoop = null;
        this.lastTime = performance.now();
        
        if (!wasmReady) {
            console.error('WebAssembly module not ready');
            return;
        }
        
        this.initializeGame();
    }

    initializeGame() {
        gameModule._init_game();
        document.getElementById('high-score').textContent = localStorage.getItem('snakeHighScore') || 0;
        this.setupEventListeners();
    }

    setupEventListeners() {
        const startPauseBtn = document.getElementById('start-pause-game');
        startPauseBtn.addEventListener('click', () => this.toggleStartPause());
        document.getElementById('reset-game').addEventListener('click', () => this.reset());
        document.getElementById('play-again').addEventListener('click', () => this.reset());

        document.addEventListener('keydown', (e) => {
            if (!this.gameRunning) return;
            
            const key = e.key.toLowerCase();
            if (key === 'w') {
                gameModule._set_direction(0, -1);
            } else if (key === 's') {
                gameModule._set_direction(0, 1);
            } else if (key === 'a') {
                gameModule._set_direction(-1, 0);
            } else if (key === 'd') {
                gameModule._set_direction(1, 0);
            }
        });
    }

    toggleStartPause() {
        const btn = document.getElementById('start-pause-game');
        if (this.gameRunning) {
            this.pause();
            btn.textContent = 'Start Game';
            btn.classList.remove('paused');
        } else {
            this.start();
            btn.textContent = 'Pause Game';
            btn.classList.add('paused');
        }
    }

    start() {
        if (this.gameRunning) return;
        gameModule._start_game();
        this.gameRunning = true;
        document.getElementById('game-over').classList.add('hidden');
        this.draw();
        this.lastTime = performance.now();
        this.gameLoop = requestAnimationFrame((timestamp) => this.gameLoopUpdate(timestamp));
    }

    gameLoopUpdate(timestamp) {
        if (!this.gameRunning) return;
        
        const elapsed = timestamp - this.lastTime;
        if (elapsed >= 80) { // Faster update rate
            const result = gameModule._update_game();
            
            if (result === -1) {
                this.gameOver();
                return;
            }
            
            if (result === 1) {
                const score = gameModule._get_score();
                document.getElementById('score').textContent = score;
            }
            
            this.draw();
            this.lastTime = timestamp;
        }
        
        this.gameLoop = requestAnimationFrame((timestamp) => this.gameLoopUpdate(timestamp));
    }

    pause() {
        if (!this.gameRunning) return;
        gameModule._set_game_running(0);
        this.gameRunning = false;
        cancelAnimationFrame(this.gameLoop);
    }

    reset() {
        gameModule._reset_game();
        this.score = 0;
        this.gameRunning = false;
        cancelAnimationFrame(this.gameLoop);
        document.getElementById('score').textContent = 0;
        document.getElementById('game-over').classList.add('hidden');
        
        const btn = document.getElementById('start-pause-game');
        btn.textContent = 'Start Game';
        btn.classList.remove('paused');
        
        this.draw();
    }

    draw() {
        // Clear canvas
        this.ctx.fillStyle = '#000';
        this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);

        // Get snake data from WebAssembly
        const snakePtr = gameModule._get_snake();
        const snakeLength = gameModule._get_snake_length();
        
        // Draw snake
        for (let i = 0; i < snakeLength; i++) {
            const x = gameModule.HEAP32[(snakePtr / 4) + (i * 2)];
            const y = gameModule.HEAP32[(snakePtr / 4) + (i * 2) + 1];
            
            if (i === 0) {
                this.ctx.fillStyle = '#34d399'; // Head
            } else {
                this.ctx.fillStyle = '#10b981'; // Body
            }
            this.ctx.fillRect(x * this.gridSize, y * this.gridSize, this.gridSize - 2, this.gridSize - 2);
        }

        // Get and draw food
        const food = gameModule._get_food();
        this.ctx.fillStyle = '#ef4444';
        this.ctx.fillRect(food.x * this.gridSize, food.y * this.gridSize, this.gridSize - 2, this.gridSize - 2);
    }

    gameOver() {
        this.gameRunning = false;
        cancelAnimationFrame(this.gameLoop);
        gameModule._set_game_running(0);
        
        const score = gameModule._get_score();
        const highScore = parseInt(localStorage.getItem('snakeHighScore') || 0);
        
        if (score > highScore) {
            localStorage.setItem('snakeHighScore', score);
            document.getElementById('high-score').textContent = score;
        }
        
        const btn = document.getElementById('start-pause-game');
        btn.textContent = 'Start Game';
        btn.classList.remove('paused');
        
        document.getElementById('final-score').textContent = score;
        document.getElementById('game-over').classList.remove('hidden');
    }
}

// Export for use
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { WasmSnakeGame, initWasmGame };
}

